### ISSUE TITLE
Issue not downloading even when file is there

### ISSUE THREAD

**Issue by DannysList** [skyme5/magzdb#104]
* magzdb version: latest
* Python version: latest
* Operating System: Win 10 

### Description

Similar issue as https://github.com/skyme5/magzdb/issues/67 just with Rock & Mineral (http://magzdb.org/j/1680). There is 248 issues and it only grabs 111 of them. the others are 0 byte pdfs. I can download these fine via the site.

**Comment by ezxpro** [comment]
Here it doesn't grab anything. I'm trying to download foreign affairs( https://magzdb.org/j/3271), it prints the downloading message as if it's working, but no file is downloaded.

**Comment by skyme5** [comment]
Fixed in [v1.1.9](https://github.com/skyme5/magzdb/releases/tag/v1.1.9), can you test if this is resolved

**Comment by ezxpro** [comment]
@skyme5 I tested it, working fine now. Except when I use curl as the downloader. When I specify wget, aria2 or no downloader at all, it downloads just fine, but when I specify curl, the old behavior follows (it skips through every download). Curl is properly installed and added to path.

But anyways, works fine now, thanks.
