### ISSUE TITLE
Possible to include other sources? https://magazinelib.com?

### ISSUE THREAD

**Issue by Rob-T** [skyme5/magzdb#13]
Just curious if it is possible to adapt the script to pull from other magazine resources, like https://magazinelib.com for example? It looks slightly more complicated (I'm not a programmer though) as magazines and releases are not organized by an ID number. That said, there are many magazines there that are not available on Magzdb and it would be a great addition!

Just a thought....

Cheers!

**Comment by skyme5** [comment]
It would not be possible to support multiple sources as it would require major refactoring in codebase.
But you can write a script for `https://magazinelib.com` to make things easier.

**Comment by Rob-T** [comment]
Cheers.
