### ISSUE TITLE
Found 0 editions of ____ 

### ISSUE THREAD

**Issue by reebevoli** [skyme5/magzdb#16]
* magzdb version:1.1.4
* Python version:3.7.3
* Operating System:Debian 10.5

### Description
This issue seems to be back again. I get 'Found Zero Editions' when running the below, but do not have any editions in the download folder. It doesn't seem to happen with all magazines though; 5423 is the only example I have at the moment

### What I Did

```
magzdb -i 5423 -f "year >= 2018" -P /home/books/magazines --downloader wget
2020-11-07 09:24:32.888 | INFO     | magzdb.magzdb:download:202 - Found 0 editions of TIME
```

**Comment by skyme5** [comment]
Seems to be working fine under Windows with 109 editions found,
```shell
$ magzdb -i 5423 -f "year >= 2018" --downloader wget
2020-11-09 14:42:48.884 | INFO     | magzdb.magzdb:download:206 - Found 109 editions of TIME
2020-11-09 14:42:48.888 | INFO     | magzdb.magzdb:download:211 - Downloading year 2020 id 4059779
```

**Comment by reebevoli** [comment]
I just tried again, but zero editions. What could be causing it to not work for me (for this magazine, other are ok) but working for you?

**Comment by skyme5** [comment]
@reebevoli, upgrade to v1.1.5 to fix the issue.
