### ISSUE TITLE
Local file server down (file.magzdb.org)

### ISSUE THREAD

**Issue by steve1977** [skyme5/magzdb#6]
I haven't tried the script, but it seems the local file server is down? According to the web page, this is the case for many months already. Does this script still function regardless? Any VPN required?

**Comment by skyme5** [comment]
This won't able to download unless the magzdb.org fixes the `file.magzdb.org`

**Comment by steve1977** [comment]
Thanks. It seems already broken for many months. Do you have any insights whether there is hope to see a fix?

I was surprised there is development activity on this in recent weeks, while it is broken for so long.

**Comment by skyme5** [comment]
It was still working in July but no !dea for when it will get fixed. 😐

**Comment by skyme5** [comment]
Hey @steve1977, seems like `magzdb.org` fixed downloading problems.
