### ISSUE TITLE
Found 0 Editions of ...

### ISSUE THREAD

**Issue by Rob-T** [skyme5/magzdb#7]
* magzdb version: 1.0.2
* Python version: 3.7.3
* Operating System: Debian 10.5

### Description

All attempts to download return 'Found 0 editions of ____ '

### What I Did

magzdb -i 4274 
magzdb -i 4274 -e 4058710
magzdb -I 2703
magzdb -i 2869
```

**Comment by skyme5** [comment]
@Rob-T this issue is resolved in latest release.

**Comment by reebevoli** [comment]
This issue seems to be back again. I get 'Found Zero Editions' when running the below, but do not have any editions in the download folder. It doesn't seem to happen with all magazines though; 5423 is the only example I have at the moment

```
magzdb -i 5423 -f "year >= 2018" -P /home/books/magazines --downloader wget
2020-11-07 09:24:32.888 | INFO     | magzdb.magzdb:download:202 - Found 0 editions of TIME
```
