### ISSUE TITLE
Retrieve correct filenames

### ISSUE THREAD

**Issue by Coool** [skyme5/magzdb#86]
* magzdb version: 1.1.6
* Python version: 3.9.2
* Operating System: Debian Current Latest

### Description

At [Компьютерра 2009 № 47-48 (811-812)](http://magzdb.org/file/45694/dl) have [Download](https://cdn1.booksdl.org/get.php?direct=true&md5=fd5635dd40e1a4feb490db8bac3e384b) link and saves it as [Компьютерра _811-812 2009-47-48] - (2009) - libgen.li.pdf, but magzdb saves it as get.phpdirecttruemd5fd5635dd40e1a4feb490db8bac3e384b.
Can you fix it?

Thanks.

**Comment by skyme5** [comment]
Thanks for using magzdb, will release a fix as soon as I get time.

**Comment by Coool** [comment]
What you think about [SuperBike Magazine 2014 № 12 (18)](http://magzdb.org/num/3816842) download [link](http://magzdb.org/file/813142/dl) which redirect to web.archive.org archived page?

**Comment by skyme5** [comment]
@Coool The link you specified redirects to a webpage, we can dump the webpage?

**Comment by Coool** [comment]
What do you suggest to do with redirect to archive and HTML pages? How name them?

**Comment by skyme5** [comment]
I think the name provided by magzdb "SuperBike Magazine 2014 № 12 (18)" should be used

**Comment by Coool** [comment]
OK. Archived and HTML pages save as {Magazine Title}.html
Have you thought about  get.phpdirecttruemd5fd5635dd40e1a4feb490db8bac3e384b issue? How to retrieve filename?
