### ISSUE TITLE
Is a range of edition possible?

### ISSUE THREAD

**Issue by Rob-T** [skyme5/magzdb#9]
* magzdb version: 1.0.4
* Python version: 3.7.3
* Operating System: Debian 10.5

### Description

Is it possible to download a range of editions, for example all between the years 2000 and 2020?

### What I Did
For example, 
magzdb -i 1234 -e 100-200, did not work.

**Comment by skyme5** [comment]
@Rob-T currently `range selection of editions` is not supported, I would very much like to implement this.

**Comment by skyme5** [comment]
Hey @Rob-T you can now use filters to download a range of editions in the latest release [v1.1.0](https://github.com/skyme5/magzdb/releases)

For your case you can use the following command
```shell
$ magzdb -i 1234 -f "eid > 100 and eid < 200"
```

Check [README](https://github.com/skyme5/magzdb#filters) for more examples.

**Comment by Rob-T** [comment]
Excellent, I will give it a try!

Cheers!
